code/10-django/project1/templalte_test/logining/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .views import login,index,login_check,index2,url_reverse,show_args,show_kwargs,test_redirect

urlpatterns = [
    path('index',index),
    path('login',login),
    path('login-check',login_check),
    path('index2',index2,name='test1'),
    path('url-reverse',url_reverse),
    path('test_redirect',test_redirect),
    re_path(r"^show_args/(\d+)/(\d+)$",show_args,name='show_args'),
    re_path(r"^show_kwargs/(?P<c>\d+)/(?P<d>\d+)$",show_kwargs,name='show_kwargs'),
]

code/10-django/project1/templalte_test/tempalte_filters/urls.py
from django.contrib import admin
from django.urls import path
from .views import tem_val,tem_tag,inhertOfChild,inhertOfPa,escape

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('temval', tem_val),
    path('temtag', tem_tag),
    path('base',inhertOfPa),
    path('child',inhertOfChild),
    path('escape',escape),
]

code/10-django/project1/templalte_test/templalte_test/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('tempalte_filters.urls')),
    path('login/', include(('logining.urls','logining'),namespace='logining')),
]

code/10-django/project1/templalte_test/logining/models.py
from django.db import models

# Create your models here.

code/10-django/project1/templalte_test/tempalte_filters/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField()
    #阅读量
    bread = models.IntegerField(default=0)
    bcomment = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)
    class Meta:
        db_table = 'bookpage_bookinfo'

class RoleInfo(models.Model):
    Rname = models.CharField(max_length=20)
    Rgender = models.BooleanField(default=True)
    Rcomment = models.CharField(max_length=200)
    Rbook = models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    class Meta:
        db_table = 'bookpage_roleinfo'

code/10-django/project1/templalte_test/logining/views.py
from django.shortcuts import render,redirect
from django.http import response,HttpResponse
from django.urls import reverse
# Create your views here.


def login_required(func_login):
    def draw(require,*args,**kwargs):
        if require.session.has_key('islogin'):
            return func_login(require,*args,**kwargs)
        else:
            return redirect('/login/login')
    return draw

@login_required
def index(request):
    return render(request, 'login/index.html')


def login(request):
    if request.session.has_key('islogin'):
         return redirect('/login/index')
    else:
        if 'username' in request.COOKIES:
            username = request.COOKIES['username']
        else:
            username = ''
    return render(request,'login/loginpage.html',{'username':username})

def login_check(request):
    username = request.POST.get('user')
    password = request.POST.get('pwd')
    remember = request.POST.get('rem')

    print(username + password)
    if username == "yujingjing" and password == "19970806":
        response = redirect('/login/index')
        if remember == "on":
            response.set_cookie('username', username, max_age=7 * 24 * 3600)
        request.session['islogin'] = True
        return response
    else:
        response = redirect('/login/login')
        return response

def index2(request):
    return render(request,'login/index2.html')

def url_reverse(request):
    return render(request,'login/url_reverse.html')

def show_args(request,a,b):
    return HttpResponse(a+':'+b)

def show_kwargs(request,c,d):
    return HttpResponse(c+ ':' + d)



def test_redirect(request):
    url = reverse('logining:show_kwargs',kwargs={'c':3,'d':4})
    return redirect(url)

code/10-django/project1/templalte_test/tempalte_filters/views.py
from django.shortcuts import render
from .models import BookInfo,RoleInfo
# Create your views here.


def tem_val(request):
    my_book = BookInfo.objects.get(id=1)
    my_list = [1,2,3,4]
    my_dict = {'rem':100}
    context = {'my_book':my_book,'my_list':my_list,'my_dict':my_dict}
    return render(request,'template_filters/temp_val.html',context)

def tem_tag(request):
    books = BookInfo.objects.all()
    return render(request,'template_filters/temp_tag.html',{'books':books})

def inhertOfPa(request):
    return render(request,'template_filters/base.html')

def inhertOfChild(request):
    return render(request,'template_filters/child.html')

def escape(request):
    return render(request,'template_filters/temp_excape.html',{'content':'<h1>这是一个标签</h1>'})

code/10-django/project1/templalte_test/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>我永远喜欢珂朵莉</h1>
    <h1>我永远喜欢奈芙莲</h1>
</body>
</html>

code/10-django/project1/templalte_test/templates/login/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>我永远喜欢珂朵莉</h1>
    <h1>我永远喜欢奈芙莲</h1>
</body>
</html>

code/10-django/project1/templalte_test/templates/login/loginpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="/login/login-check">
        {% crsf_token %}
        <label>用户名</label>
        <input type="text" name="user" value="{{user}}"> <br />
        <label>用户名</label>
        <input type="text" name="pwd"> <br />
        <label>是否记住密码</label>
        <input type="checkbox" name ="rem"}}>
        <input type="submit" value="登录"> <br>
    </form>
    {{content}}

</body>
</html>

code/10-django/project1/templalte_test/templates/login/url_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    url链接：
    <a href="/login/index2">回归首页</a><br />
    url反向解析生成:
    <a href="{% url 'logining:test1' %}">回归首页</a><br />
    动态args反向解析：
    <a href="{% url 'logining:show_args' 1 2 %}">login/show_args/1/2</a><br />
    动态kwargs反向解析：
    <a href="{% url 'logining:show_kwargs' c=3 d=4　%}">login/show_kwargs/3/4</a>
</body>
</html>

code/10-django/project1/templalte_test/templates/template_filters/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>网页头部</h1>
    {% block b1 %}
    <h1>这是父模板的h1</h1>
    {% endblock b1 %}

    {% block b2 %}
    <h2>这是父模板的h2</h2>
    {% endblock b2 %}
    <h1>网页尾部</h1>
</body>
</html>

code/10-django/project1/templalte_test/templates/template_filters/child.html
{% extends 'template_filters/base.html' %}

{% block b1 %}
    {{block.super }}
    <h1>这是子模板的h1</h1>
{% endblock b1 %}

{% block b2 %}
    {{block.super }}
    <h2>这是子模板的h2</h2>
{% endblock b2 %}

code/10-django/project1/templalte_test/templates/template_filters/temp_excape.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    默认转义：
    <h1>{{content}}</h1><br />
    第一种不转义方法:
    <h1>{{content|safe}}</h1><br />
    第二种不转义方法
    {% autoescape off %}
    <h1>{{content}}</h1>
    {% endautoescape %}
</body>
</html>

code/10-django/project1/templalte_test/templates/template_filters/temp_tag.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load filters %}
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        .style1{
            background-color: #00FF00;
        }
        .style2{
            background-color: cyan;
        }
    </style>
</head>
<body>
    <ul>
<!--        {% for book in books %}-->
<!--            {% if book.id <= 3 %}-->
<!--                <li class="style1">{{forloop.counter}}&#45;&#45;{{book.btitle}}&#45;&#45;{{book.bpub_date|date:'y年-m月-d日'}}</li>-->
<!--            {% else %}-->
<!--                <li class="style2">{{forloop.counter}}&#45;&#45;{{book.btitle}}&#45;&#45;{{book.bpub_date|date:'y年-m月-d日'}}</li>-->
<!--            {% endif %}-->
<!--        {% endfor %}-->
        {% for book in books %}
            {% if book.id|mod:2 %}
                <li class="style1">{{forloop.counter}}--{{book.btitle}}--{{book.bpub_date|date:'y年-m月-d日'}}</li>
            {% else %}
                <li class="style2">{{forloop.counter}}--{{book.btitle}}--{{book.bpub_date|date:'y年-m月-d日'}}</li>
            {% endif %}
        {% endfor %}
    </ul>
    default过滤器<br />
    {{content|default:'hello'}}
</body>
</html>

code/10-django/project1/templalte_test/templates/template_filters/temp_val.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>模板变量</h2>
    <ul>
        <li>{{my_book.btitle}}</li>
        <li>{{my_list.2}}</li>
        <li>{{my_dict.rem}}</li>
    </ul>
</body>
</html>